// User-related APIs

export const FETCH_USER_API = 'FETCH_USER_API'
export const USER_LOGIN_API='USER_LOGIN_API'
export const FETCH_USERS_BY_PROJECT_ID_API = 'FETCH_USERS_BY_PROJECT_ID_API'
// Task-related APIs
export const FETCH_TASK_TYPE_API='FETCH_TASK_TYPE_API'
export const FETCH_PRIORITY_API = 'FETCH_PRIORITY_API'
export const FETCH_STATUS_API = 'FETCH_STATUS_API'
export const CREATE_TASK_API = 'CREATE_TASK_API'
export const UPDATE_STATUS_API = 'UPDATE_STATUS_API'
export const FETCH_TASK_DETAIL_API = 'FETCH_TASK_DETAIL_API'
export const UPDATE_TASK_DETAIL_API = 'UPDATE_TASK_DETAIL_API'
export const REMOVE_TASK_API = 'REMOVE_TASK_API'

//Project-related APIs
export const FETCH_ALL_PROJECT_API = 'FETCH_ALL_PROJECT_API'
export const REMOVE_USER_FROM_PROJECT_API = 'REMOVE_USER_FROM_PROJECT_API';
export const ASSIGN_USER_FORM_PROJECT_API = 'ASSIGN_USER_FORM_PROJECT_API'
export const FETCH_CATEGORY_PROJECT_API = 'FETCH_CATEGORY_PROJECT_API'
export const CREATE_PROJECT_API ='CREATE_PROJECT_API'
export const DELETE_PROJECT_API = 'DELETE_PROJECT_API'
export const UPDATE_PROJECT_API = 'UPDATE_PROJECT_API'
export const FETCH_PROJECT_DETAIL_API = 'FETCH_PROJECT_DETAIL_API'

//Comment-related APIs

export const DELETE_COMMENT_API='DELETE_COMMENT_API'

//Spinner
export const LOADING_SPINNER = 'LOADING_SPINNER'
//Modal
export const TASK_CREATE_MODAL='TASK_CREATE_MODAL'
export const TASK_SEARCH_MODAL='TASK_SEARCH_MODAL'
export const UPDATE_MODAL='UPDATE_MODAL'
export const TIME_TRACKING_MODAL = 'TIME_TRACKING_MODAL'
export const DELETE_TASK_MODAL = 'DELETE_TASK_MODAL'
export const DELETE_COMMENT_MODAL = 'CONFIRM_MODAL'